// 5250ng - A modern IBM TN5250 terminal emulator
// Copyright (C) 2025-2026 Remi GASCOU (Podalirius)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include <QJsonArray>
#include <QJsonObject>
#include <QString>

namespace agent {

// ---------------------------------------------------------------------------
// run_5250script — execute a script on the terminal
// ---------------------------------------------------------------------------

inline const QString kToolRunScript = QStringLiteral("run_5250script");

inline const QString kToolRunScriptDescription = QStringLiteral(
    "Execute a 5250script on the current terminal session. "
    "The script interacts with the live AS/400 session. "
    "Use this to run scripts generated by generate_5250script.");

inline QJsonObject toolRunScriptSchema() {
    QJsonObject scriptProp;
    scriptProp["type"] = "string";
    scriptProp["description"] = "The 5250script source code to execute";

    QJsonObject properties;
    properties["script"] = scriptProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"script"};
    return schema;
}

// ---------------------------------------------------------------------------
// generate_5250script — generate a script via subagent
// ---------------------------------------------------------------------------

inline const QString kToolGenerateScript = QStringLiteral("generate_5250script");

inline const QString kToolGenerateScriptDescription = QStringLiteral(
    "Generate a 5250script from a natural language task description. "
    "A specialized subagent with full knowledge of the 5250script language "
    "will generate the script code. The generated script is returned as text "
    "which you can then pass to run_5250script to execute it. "
    "Use this for any terminal automation task.");

inline QJsonObject toolGenerateScriptSchema() {
    QJsonObject taskProp;
    taskProp["type"] = "string";
    taskProp["description"] =
        "Natural language description of the task the script should perform";

    QJsonObject properties;
    properties["task"] = taskProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"task"};
    return schema;
}

// ---------------------------------------------------------------------------
// read_file — read a file from the local filesystem
// ---------------------------------------------------------------------------

inline const QString kToolReadFile = QStringLiteral("read_file");

inline const QString kToolReadFileDescription = QStringLiteral(
    "Read the contents of a file from the local filesystem. "
    "Returns the full text content of the file.");

inline QJsonObject toolReadFileSchema() {
    QJsonObject pathProp;
    pathProp["type"] = "string";
    pathProp["description"] = "The absolute or relative path to the file to read";

    QJsonObject properties;
    properties["path"] = pathProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"path"};
    return schema;
}

// ---------------------------------------------------------------------------
// write_file — write content to a file on the local filesystem
// ---------------------------------------------------------------------------

inline const QString kToolWriteFile = QStringLiteral("write_file");

inline const QString kToolWriteFileDescription = QStringLiteral(
    "Write content to a file on the local filesystem. "
    "Creates the file if it does not exist, or overwrites it if it does.");

inline QJsonObject toolWriteFileSchema() {
    QJsonObject pathProp;
    pathProp["type"] = "string";
    pathProp["description"] = "The absolute or relative path to the file to write";

    QJsonObject contentProp;
    contentProp["type"] = "string";
    contentProp["description"] = "The text content to write to the file";

    QJsonObject properties;
    properties["path"] = pathProp;
    properties["content"] = contentProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"path", "content"};
    return schema;
}

// ---------------------------------------------------------------------------
// read_screen — read the current terminal screen content
// ---------------------------------------------------------------------------

inline const QString kToolReadScreen = QStringLiteral("read_screen");

inline const QString kToolReadScreenDescription = QStringLiteral(
    "Read the current content of the 5250 terminal screen. "
    "Returns the full text of all rows on the screen. "
    "Use this to see what is displayed after running a script or at any time.");

inline QJsonObject toolReadScreenSchema() {
    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = QJsonObject();
    return schema;
}

// ---------------------------------------------------------------------------
// list_files — list files and directories
// ---------------------------------------------------------------------------

inline const QString kToolListFiles = QStringLiteral("list_files");

inline const QString kToolListFilesDescription = QStringLiteral(
    "List files and directories at a given path on the local filesystem. "
    "Returns names, types (file or directory), and sizes.");

inline QJsonObject toolListFilesSchema() {
    QJsonObject pathProp;
    pathProp["type"] = "string";
    pathProp["description"] = "The directory path to list. Defaults to current directory if empty.";

    QJsonObject properties;
    properties["path"] = pathProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    return schema;
}

// ---------------------------------------------------------------------------
// send_keys — send keystrokes to the terminal
// ---------------------------------------------------------------------------

inline const QString kToolSendKeys = QStringLiteral("send_keys");

inline const QString kToolSendKeysDescription = QStringLiteral(
    "Send one or more keystrokes to the terminal session. "
    "Accepts a space-separated list of key names. "
    "Supported keys: ENTER, F1-F24, TAB, BACKSPACE, PAGEUP, PAGEDOWN, "
    "HOME, END, INSERT, DELETE, ESCAPE, UP, DOWN, LEFT, RIGHT, FIELDEXIT. "
    "PAGEDOWN shows the next page (5250 Roll Up), PAGEUP the previous page (Roll Down). "
    "Text can be typed by wrapping in quotes, e.g. send_keys with keys='\"hello\" ENTER'. "
    "This is lighter weight than run_5250script for simple key presses.");

inline QJsonObject toolSendKeysSchema() {
    QJsonObject keysProp;
    keysProp["type"] = "string";
    keysProp["description"] =
        "Space-separated key names to send, e.g. 'F3' or 'Tab \"mytext\" Enter'";

    QJsonObject properties;
    properties["keys"] = keysProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"keys"};
    return schema;
}

// ---------------------------------------------------------------------------
// clear_inputs — clear all input fields on the screen
// ---------------------------------------------------------------------------

inline const QString kToolClearInputs = QStringLiteral("clear_inputs");

inline const QString kToolClearInputsDescription = QStringLiteral(
    "Clear all input fields on the current terminal screen. "
    "Resets every non-protected field to its original empty state, "
    "clears all Modified Data Tags (MDT), and moves the cursor back "
    "to the initial cursor position. Equivalent to the Erase Input key.");

inline QJsonObject toolClearInputsSchema() {
    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = QJsonObject();
    return schema;
}

// ---------------------------------------------------------------------------
// get_cursor_position — get the current cursor position
// ---------------------------------------------------------------------------

inline const QString kToolGetCursorPosition = QStringLiteral("get_cursor_position");

inline const QString kToolGetCursorPositionDescription = QStringLiteral(
    "Get the current cursor position on the terminal screen. "
    "Returns the row and column (0-based) of the cursor.");

inline QJsonObject toolGetCursorPositionSchema() {
    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = QJsonObject();
    return schema;
}

// ---------------------------------------------------------------------------
// get_field_at — get field information at a screen position
// ---------------------------------------------------------------------------

inline const QString kToolGetFieldAt = QStringLiteral("get_field_at");

inline const QString kToolGetFieldAtDescription = QStringLiteral(
    "Get information about the input field at a given screen position. "
    "Returns the field's start position, length, whether it is protected (read-only), "
    "and its current text content. Returns an error if no field exists at the position.");

inline QJsonObject toolGetFieldAtSchema() {
    QJsonObject rowProp;
    rowProp["type"] = "integer";
    rowProp["description"] = "Row on the screen (0-based)";

    QJsonObject colProp;
    colProp["type"] = "integer";
    colProp["description"] = "Column on the screen (0-based)";

    QJsonObject properties;
    properties["row"] = rowProp;
    properties["col"] = colProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"row", "col"};
    return schema;
}

// ---------------------------------------------------------------------------
// connect — connect to an AS/400 host
// ---------------------------------------------------------------------------

inline const QString kToolConnect = QStringLiteral("connect");

inline const QString kToolConnectDescription = QStringLiteral(
    "Connect to an AS/400 (IBM i) host via TN5250. "
    "Creates a new terminal session and establishes the connection. "
    "Returns when the connection is established and the terminal is ready.");

inline QJsonObject toolConnectSchema() {
    QJsonObject hostProp;
    hostProp["type"] = "string";
    hostProp["description"] = "Hostname or IP address of the AS/400 system";

    QJsonObject portProp;
    portProp["type"] = "integer";
    portProp["description"] = "TCP port number (default 23)";

    QJsonObject tlsProp;
    tlsProp["type"] = "boolean";
    tlsProp["description"] = "Use TLS/SSL encryption (default false)";

    QJsonObject properties;
    properties["hostname"] = hostProp;
    properties["port"] = portProp;
    properties["useTLS"] = tlsProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"hostname"};
    return schema;
}

// ---------------------------------------------------------------------------
// login — auto-login to the AS/400 using username and password
// ---------------------------------------------------------------------------

inline const QString kToolLogin = QStringLiteral("login");

inline const QString kToolLoginDescription = QStringLiteral(
    "Log in to the AS/400 system using a username and password. "
    "Waits for the sign-on screen, types the credentials, and presses Enter. "
    "Requires an active terminal connection (use the connect tool first).");

inline QJsonObject toolLoginSchema() {
    QJsonObject userProp;
    userProp["type"] = "string";
    userProp["description"] = "AS/400 user profile name";

    QJsonObject passProp;
    passProp["type"] = "string";
    passProp["description"] = "Password for the user profile";

    QJsonObject properties;
    properties["username"] = userProp;
    properties["password"] = passProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"username", "password"};
    return schema;
}

// ---------------------------------------------------------------------------
// MCP-only tools (not sent to AI providers, only exposed via MCP server)
// ---------------------------------------------------------------------------

// create_session — create a new MCP-controlled TN5250 session
inline const QString kToolCreateSession = QStringLiteral("create_session");

inline const QString kToolCreateSessionDescription = QStringLiteral(
    "Create a new TN5250 terminal session and connect to an AS/400 host. "
    "Returns a session_id that must be used in subsequent tool calls to "
    "target this session. The session appears as a read-only tab in the UI.");

inline QJsonObject toolCreateSessionSchema() {
    QJsonObject hostProp;
    hostProp["type"] = "string";
    hostProp["description"] = "Hostname or IP address of the AS/400 system";

    QJsonObject portProp;
    portProp["type"] = "integer";
    portProp["description"] = "TCP port number (default 23)";

    QJsonObject tlsProp;
    tlsProp["type"] = "boolean";
    tlsProp["description"] = "Use TLS/SSL encryption (default false)";

    QJsonObject properties;
    properties["hostname"] = hostProp;
    properties["port"] = portProp;
    properties["useTLS"] = tlsProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"hostname"};
    return schema;
}

// close_session — close an MCP-controlled session
inline const QString kToolCloseSession = QStringLiteral("close_session");

inline const QString kToolCloseSessionDescription = QStringLiteral(
    "Close an MCP-controlled terminal session. "
    "Disconnects from the host and removes the tab.");

inline QJsonObject toolCloseSessionSchema() {
    QJsonObject sidProp;
    sidProp["type"] = "string";
    sidProp["description"] = "Session ID returned by create_session";

    QJsonObject properties;
    properties["session_id"] = sidProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"session_id"};
    return schema;
}

// list_sessions — list all MCP-managed sessions
inline const QString kToolListSessions = QStringLiteral("list_sessions");

inline const QString kToolListSessionsDescription = QStringLiteral(
    "List all MCP-managed terminal sessions with their IDs, "
    "hostnames, ports, and connection status.");

inline QJsonObject toolListSessionsSchema() {
    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = QJsonObject();
    return schema;
}

// screenshot — capture terminal screen as PNG
inline const QString kToolScreenshot = QStringLiteral("screenshot");

inline const QString kToolScreenshotDescription = QStringLiteral(
    "Capture the terminal screen of a session as a PNG image. "
    "Saves the screenshot to the specified file path. "
    "Useful for generating visual reports.");

inline QJsonObject toolScreenshotSchema() {
    QJsonObject sidProp;
    sidProp["type"] = "string";
    sidProp["description"] = "Session ID returned by create_session";

    QJsonObject pathProp;
    pathProp["type"] = "string";
    pathProp["description"] = "File path where the PNG screenshot will be saved";

    QJsonObject properties;
    properties["session_id"] = sidProp;
    properties["path"] = pathProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"session_id", "path"};
    return schema;
}

// ---------------------------------------------------------------------------
// press_key — press a single key on the terminal
// ---------------------------------------------------------------------------

inline const QString kToolPressKey = QStringLiteral("press_key");

inline const QString kToolPressKeyDescription = QStringLiteral(
    "Press a single key on the terminal session. "
    "Accepts one key name. "
    "Supported keys: ENTER, F1-F24, TAB, BACKTAB, BACKSPACE, DELETE, "
    "INSERT, HOME, END, ESCAPE, PAGEUP, PAGEDOWN, "
    "FIELDPLUS, FIELDMINUS, FIELDEXIT, DUP, "
    "ERASEINPUT, ERASEFIELD, ERASEEOF, "
    "ATTN, SYSREQ, HELP, CLEAR, PRINT, "
    "UP, DOWN, LEFT, RIGHT. "
    "PAGEDOWN shows the next page (5250 Roll Up), PAGEUP the previous page (Roll Down).");

inline QJsonObject toolPressKeySchema() {
    QJsonObject keyProp;
    keyProp["type"] = "string";
    keyProp["description"] =
        "The key name to press, e.g. 'ENTER' or 'F5'";

    QJsonObject properties;
    properties["key"] = keyProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"key"};
    return schema;
}

// ---------------------------------------------------------------------------
// type_text — type a string at the current cursor position
// ---------------------------------------------------------------------------

inline const QString kToolTypeText = QStringLiteral("type_text");

inline const QString kToolTypeTextDescription = QStringLiteral(
    "Type a text string at the current cursor position on the terminal. "
    "The text is entered character by character into the current field. "
    "Does not press Enter or any other key after typing.");

inline QJsonObject toolTypeTextSchema() {
    QJsonObject textProp;
    textProp["type"] = "string";
    textProp["description"] = "The text string to type at the current cursor position";

    QJsonObject properties;
    properties["text"] = textProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"text"};
    return schema;
}

// ---------------------------------------------------------------------------
// press_keys — press a sequence of keys on the terminal
// ---------------------------------------------------------------------------

inline const QString kToolPressKeys = QStringLiteral("press_keys");

inline const QString kToolPressKeysDescription = QStringLiteral(
    "Press a sequence of keys on the terminal session. "
    "Accepts an ordered array of key names, executed one after another. "
    "Supported keys: ENTER, F1-F24, TAB, BACKTAB, BACKSPACE, DELETE, "
    "INSERT, HOME, END, ESCAPE, PAGEUP, PAGEDOWN, "
    "FIELDPLUS, FIELDMINUS, FIELDEXIT, DUP, "
    "ERASEINPUT, ERASEFIELD, ERASEEOF, "
    "ATTN, SYSREQ, HELP, CLEAR, PRINT, "
    "UP, DOWN, LEFT, RIGHT. "
    "PAGEDOWN shows the next page (5250 Roll Up), PAGEUP the previous page (Roll Down).");

inline QJsonObject toolPressKeysSchema() {
    QJsonObject keyItem;
    keyItem["type"] = "string";

    QJsonObject keysProp;
    keysProp["type"] = "array";
    keysProp["items"] = keyItem;
    keysProp["description"] =
        "Ordered list of key names to press, e.g. [\"F5\", \"ENTER\"]";

    QJsonObject properties;
    properties["keys"] = keysProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"keys"};
    return schema;
}

// ---------------------------------------------------------------------------
// set_cursor_position — move cursor to an absolute screen position
// ---------------------------------------------------------------------------

inline const QString kToolSetCursorPosition = QStringLiteral("set_cursor_position");

inline const QString kToolSetCursorPositionDescription = QStringLiteral(
    "Move the cursor to an absolute position on the terminal screen. "
    "Row and column are 0-based.");

inline QJsonObject toolSetCursorPositionSchema() {
    QJsonObject rowProp;
    rowProp["type"] = "integer";
    rowProp["description"] = "Target row on the screen (0-based)";

    QJsonObject colProp;
    colProp["type"] = "integer";
    colProp["description"] = "Target column on the screen (0-based)";

    QJsonObject properties;
    properties["row"] = rowProp;
    properties["col"] = colProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"row", "col"};
    return schema;
}

// ---------------------------------------------------------------------------
// move_cursor — move cursor relative to current position
// ---------------------------------------------------------------------------

inline const QString kToolMoveCursor = QStringLiteral("move_cursor");

inline const QString kToolMoveCursorDescription = QStringLiteral(
    "Move the cursor relative to its current position. "
    "Positive rows move down, negative move up. "
    "Positive cols move right, negative move left. "
    "Either parameter can be omitted to move in only one direction.");

inline QJsonObject toolMoveCursorSchema() {
    QJsonObject rowsProp;
    rowsProp["type"] = "integer";
    rowsProp["description"] = "Number of rows to move (positive=down, negative=up, default 0)";

    QJsonObject colsProp;
    colsProp["type"] = "integer";
    colsProp["description"] = "Number of columns to move (positive=right, negative=left, default 0)";

    QJsonObject properties;
    properties["rows"] = rowsProp;
    properties["cols"] = colsProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    return schema;
}

// ---------------------------------------------------------------------------
// get_screen_size — return screen dimensions
// ---------------------------------------------------------------------------

inline const QString kToolGetScreenSize = QStringLiteral("get_screen_size");

inline const QString kToolGetScreenSizeDescription = QStringLiteral(
    "Get the dimensions of the terminal screen. "
    "Returns the number of rows and columns.");

inline QJsonObject toolGetScreenSizeSchema() {
    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = QJsonObject();
    return schema;
}

// ---------------------------------------------------------------------------
// find_text — find text position on screen
// ---------------------------------------------------------------------------

inline const QString kToolFindText = QStringLiteral("find_text");

inline const QString kToolFindTextDescription = QStringLiteral(
    "Find the position of a text string on the terminal screen. "
    "Searches the entire screen and returns the row and column (0-based) "
    "of the first occurrence. Returns all occurrences if multiple are found.");

inline QJsonObject toolFindTextSchema() {
    QJsonObject textProp;
    textProp["type"] = "string";
    textProp["description"] = "The text string to search for on the screen";

    QJsonObject properties;
    properties["text"] = textProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"text"};
    return schema;
}

// ---------------------------------------------------------------------------
// wait_for_text — wait until text appears on screen
// ---------------------------------------------------------------------------

inline const QString kToolWaitForText = QStringLiteral("wait_for_text");

inline const QString kToolWaitForTextDescription = QStringLiteral(
    "Wait until a specific text string appears on the terminal screen. "
    "Blocks until the text is found or the timeout expires. "
    "Default timeout is 30 seconds.");

inline QJsonObject toolWaitForTextSchema() {
    QJsonObject textProp;
    textProp["type"] = "string";
    textProp["description"] = "The text string to wait for on the screen";

    QJsonObject timeoutProp;
    timeoutProp["type"] = "integer";
    timeoutProp["description"] = "Timeout in milliseconds (default 30000)";

    QJsonObject properties;
    properties["text"] = textProp;
    properties["timeout"] = timeoutProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"text"};
    return schema;
}

// ---------------------------------------------------------------------------
// read_line — read a single line from the screen
// ---------------------------------------------------------------------------

inline const QString kToolReadLine = QStringLiteral("read_line");

inline const QString kToolReadLineDescription = QStringLiteral(
    "Read a single line of text from the terminal screen at the given row. "
    "Row is 0-based. Returns the full text content of that row.");

inline QJsonObject toolReadLineSchema() {
    QJsonObject rowProp;
    rowProp["type"] = "integer";
    rowProp["description"] = "Row number to read (0-based)";

    QJsonObject properties;
    properties["row"] = rowProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"row"};
    return schema;
}

// ---------------------------------------------------------------------------
// read_region — read a rectangular region of the screen
// ---------------------------------------------------------------------------

inline const QString kToolReadRegion = QStringLiteral("read_region");

inline const QString kToolReadRegionDescription = QStringLiteral(
    "Read a rectangular region of text from the terminal screen. "
    "All coordinates are 0-based. Returns the text content of the region.");

inline QJsonObject toolReadRegionSchema() {
    QJsonObject rowProp;
    rowProp["type"] = "integer";
    rowProp["description"] = "Starting row (0-based)";

    QJsonObject colProp;
    colProp["type"] = "integer";
    colProp["description"] = "Starting column (0-based)";

    QJsonObject numRowsProp;
    numRowsProp["type"] = "integer";
    numRowsProp["description"] = "Number of rows to read";

    QJsonObject numColsProp;
    numColsProp["type"] = "integer";
    numColsProp["description"] = "Number of columns to read";

    QJsonObject properties;
    properties["row"] = rowProp;
    properties["col"] = colProp;
    properties["numRows"] = numRowsProp;
    properties["numCols"] = numColsProp;

    QJsonObject schema;
    schema["type"] = "object";
    schema["properties"] = properties;
    schema["required"] = QJsonArray{"row", "col", "numRows", "numCols"};
    return schema;
}

// ---------------------------------------------------------------------------
// Provider-specific tool array builders (defined in tool_definitions.cpp)
// ---------------------------------------------------------------------------

QJsonArray anthropicToolsArray();
QJsonArray openaiToolsArray();

} // namespace agent
